add window.event in onKey
This port dae/anki@ddb4db0c9618d67d22a35bd7eb1baf664a3d2f6d
It's related to the fact that now, onKey expect an event.

And it'll make disappear the line "JS error on line 40: Uncaught
TypeError: Cannot read property 'which' of undefined" which keeps
popping when I run anki in a terminal with your addon